---
- name: yum upgrade all
  yum: name=* state=latest

- name: yum install fundamental packages
  yum: name={{ item }} state=present
  with_items:
    - "@development"
    - policycoreutils-python
    - epel-release
    - chrony

- name: yum install ansible
  yum: name=ansible state=present

- name: Set SELinux turned off
  selinux: state=disabled

- name: Start chrony(ex.ntpd)
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Start firewalld(ex.iptables)
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Enable ports
  firewalld: service={{ item }} permanent=true state=enabled
  with_items:
    - http
    - https
    - smtp
  notify: restart firewalld
