---
- name: Configure store
  shell: php /var/www/html/magento2/bin/magento setup:install --base-url={{ base_url }} --db-host=localhost --db-name={{ db_name }} --db-user={{ db_user }} --db-password={{ db_password}} --backend-frontname={{ backend_frontname }} --admin-firstname={{ admin_firstname }} --admin-lastname={{ admin_lastname }} --admin-email={{ admin_email }} --admin-user={{ admin_user }} --admin-password={{ admin_password }} --language={{ m2_language }} --currency={{ m2_currency }} --timezone={{ m2_timezone }} --use-rewrites=1
  become: false

# /magento2/var/composer_home/に新規でauthを設置
- name: set composer auth.json
  template: src=auth.json.j2 dest=/var/www/html/magento2/var/composer_home/auth.json owner=vagrant group=vagrant mode=0600
  become: false

# /magento2/var/composer_home/に向けて設定再更新
- name: composer use packagist.jp(https)
  shell: composer config -g repositories.packagist composer https://packagist.jp
  become: false

- name: Deploy sample data
  shell: php /var/www/html/magento2/bin/magento sampledata:deploy
  become: false

- name: Show sample data
  shell: php /var/www/html/magento2/bin/magento setup:upgrade
  become: false

# - name: Set Developer mode
#   shell: php /var/www/html/magento2/bin/magento deploy:mode:set developer
#   become: false

- name: Reindex index
  shell: php /var/www/html/magento2/bin/magento indexer:reindex
  become: false

- name: Flush all cache
  shell: php /var/www/html/magento2/bin/magento cache:flush
  become: false
